// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: grpcauth.proto

package grpcauth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageServiceClient interface {
	ServeJWT(ctx context.Context, in *MessageJWT, opts ...grpc.CallOption) (*ReplyJWT, error)
	SendToAnalitic(ctx context.Context, in *MessageAnal, opts ...grpc.CallOption) (*ReplyAnal, error)
}

type messageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServiceClient(cc grpc.ClientConnInterface) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) ServeJWT(ctx context.Context, in *MessageJWT, opts ...grpc.CallOption) (*ReplyJWT, error) {
	out := new(ReplyJWT)
	err := c.cc.Invoke(ctx, "/MessageService/ServeJWT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) SendToAnalitic(ctx context.Context, in *MessageAnal, opts ...grpc.CallOption) (*ReplyAnal, error) {
	out := new(ReplyAnal)
	err := c.cc.Invoke(ctx, "/MessageService/SendToAnalitic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServiceServer is the server API for MessageService service.
// All implementations must embed UnimplementedMessageServiceServer
// for forward compatibility
type MessageServiceServer interface {
	ServeJWT(context.Context, *MessageJWT) (*ReplyJWT, error)
	SendToAnalitic(context.Context, *MessageAnal) (*ReplyAnal, error)
	mustEmbedUnimplementedMessageServiceServer()
}

// UnimplementedMessageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMessageServiceServer struct {
}

func (UnimplementedMessageServiceServer) ServeJWT(context.Context, *MessageJWT) (*ReplyJWT, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServeJWT not implemented")
}
func (UnimplementedMessageServiceServer) SendToAnalitic(context.Context, *MessageAnal) (*ReplyAnal, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendToAnalitic not implemented")
}
func (UnimplementedMessageServiceServer) mustEmbedUnimplementedMessageServiceServer() {}

// UnsafeMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServiceServer will
// result in compilation errors.
type UnsafeMessageServiceServer interface {
	mustEmbedUnimplementedMessageServiceServer()
}

func RegisterMessageServiceServer(s grpc.ServiceRegistrar, srv MessageServiceServer) {
	s.RegisterService(&MessageService_ServiceDesc, srv)
}

func _MessageService_ServeJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageJWT)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).ServeJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MessageService/ServeJWT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).ServeJWT(ctx, req.(*MessageJWT))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_SendToAnalitic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageAnal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).SendToAnalitic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MessageService/SendToAnalitic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).SendToAnalitic(ctx, req.(*MessageAnal))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageService_ServiceDesc is the grpc.ServiceDesc for MessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServeJWT",
			Handler:    _MessageService_ServeJWT_Handler,
		},
		{
			MethodName: "SendToAnalitic",
			Handler:    _MessageService_SendToAnalitic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcauth.proto",
}
