version: "3.7"
services:

  db:
    image: postgres:14.4
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'test_db'
    volumes:
      - ./init-test-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: always
    ports:
      - 8082:8080