// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: grpcauth.proto

package grpcServer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JWTChekRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jwttoken string `protobuf:"bytes,1,opt,name=jwttoken,proto3" json:"jwttoken,omitempty"`
}

func (x *JWTChekRequest) Reset() {
	*x = JWTChekRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcauth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JWTChekRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTChekRequest) ProtoMessage() {}

func (x *JWTChekRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcauth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTChekRequest.ProtoReflect.Descriptor instead.
func (*JWTChekRequest) Descriptor() ([]byte, []int) {
	return file_grpcauth_proto_rawDescGZIP(), []int{0}
}

func (x *JWTChekRequest) GetJwttoken() string {
	if x != nil {
		return x.Jwttoken
	}
	return ""
}

type JWTChekResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *JWTChekResponse) Reset() {
	*x = JWTChekResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcauth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JWTChekResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTChekResponse) ProtoMessage() {}

func (x *JWTChekResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcauth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTChekResponse.ProtoReflect.Descriptor instead.
func (*JWTChekResponse) Descriptor() ([]byte, []int) {
	return file_grpcauth_proto_rawDescGZIP(), []int{1}
}

func (x *JWTChekResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_grpcauth_proto protoreflect.FileDescriptor

var file_grpcauth_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x72, 0x70, 0x63, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0a, 0x67, 0x72, 0x70, 0x63, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x2c, 0x0a, 0x0e,
	0x4a, 0x57, 0x54, 0x43, 0x68, 0x65, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x6a, 0x77, 0x74, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6a, 0x77, 0x74, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x21, 0x0a, 0x0f, 0x4a, 0x57,
	0x54, 0x43, 0x68, 0x65, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x32, 0x56, 0x0a,
	0x0e, 0x4a, 0x57, 0x54, 0x43, 0x68, 0x65, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x44, 0x0a, 0x07, 0x4a, 0x57, 0x54, 0x63, 0x68, 0x65, 0x6b, 0x12, 0x1a, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4a, 0x57, 0x54, 0x43, 0x68, 0x65, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x4a, 0x57, 0x54, 0x43, 0x68, 0x65, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpcauth_proto_rawDescOnce sync.Once
	file_grpcauth_proto_rawDescData = file_grpcauth_proto_rawDesc
)

func file_grpcauth_proto_rawDescGZIP() []byte {
	file_grpcauth_proto_rawDescOnce.Do(func() {
		file_grpcauth_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcauth_proto_rawDescData)
	})
	return file_grpcauth_proto_rawDescData
}

var file_grpcauth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpcauth_proto_goTypes = []interface{}{
	(*JWTChekRequest)(nil),  // 0: grpcServer.JWTChekRequest
	(*JWTChekResponse)(nil), // 1: grpcServer.JWTChekResponse
}
var file_grpcauth_proto_depIdxs = []int32{
	0, // 0: grpcServer.JWTChekService.JWTchek:input_type -> grpcServer.JWTChekRequest
	1, // 1: grpcServer.JWTChekService.JWTchek:output_type -> grpcServer.JWTChekResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcauth_proto_init() }
func file_grpcauth_proto_init() {
	if File_grpcauth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpcauth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JWTChekRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcauth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JWTChekResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcauth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcauth_proto_goTypes,
		DependencyIndexes: file_grpcauth_proto_depIdxs,
		MessageInfos:      file_grpcauth_proto_msgTypes,
	}.Build()
	File_grpcauth_proto = out.File
	file_grpcauth_proto_rawDesc = nil
	file_grpcauth_proto_goTypes = nil
	file_grpcauth_proto_depIdxs = nil
}
